# Generated by Django 4.2.7 on 2023-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(default="not specified", max_length=120),
        ),
        migrations.AddField(
            model_name="book",
            name="pic",
            field=models.ImageField(default="book.png", upload_to="books"),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_type",
            field=models.CharField(
                choices=[
                    ("hardcover", "Hardcover"),
                    ("ebook", "E-book"),
                    ("audiobook", "Audiobook"),
                ],
                default="hardcover",
                max_length=12,
            ),
        ),
    ]
