# Generated by Django 4.2.7 on 2023-11-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pic",
            field=models.ImageField(default="profilepic.png", upload_to="customers"),
        ),
    ]
