# Generated by Django 4.2.7 on 2023-11-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="book.png", upload_to="food"),
        ),
    ]
